<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.ttn</groupId>
	<artifactId>MyProject</artifactId>
	<packaging>pom</packaging>
	<version>1.0-SNAPSHOT</version>
	<properties>
		<!--Java 21 as Compiler for source and target-->
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<name>MyProject</name>
	<url>http://maven.apache.org</url>

	<!--Ques-3-->
	<!-- Adding JitPack repository for fetching dependencies from GitHub -->
	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

	<dependencies>


	</dependencies>
	<!--Ques-6-->
	<!-- Defining modules for a multi-module Maven project -->
	<modules>
		<module>child1</module>

	</modules>
</project>